name: Node CI

environment: &environment
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [8, 10, 12]

on:
  push:
    branches:
      - master
    paths:
      - '*.ts'
  pull_request:
    paths:
      - '*.ts'

jobs:
  lint:
    name: eslint
    <<: *environment
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
  test:
    name: Library test
    <<: *environment
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm ci
        npm run test
      env:
        CI: true
